name: CMake Cross-Platform CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B build -S . \
            ${{ runner.os == 'Linux' && format('-DCMAKE_BUILD_TYPE={0}', matrix.build_type) || '' }} \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}